### ISSUE TITLE
Failed to recognise explore intent

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#17]
Hi Fabio,

Q: "Explore butterfly".

the nlp.ask(text) function return this: 
{complete: true, intent: "None", entities: []}.

But it does work for "Explore frog" and return the full response.Since there is no api call for explore species, I am wondering how should I handle the error for invalid species.

**Comment by iosonofabio** [comment]
I think it's arguable whether the intent should be detected here, because the sentence is very short and entity capture cannot happen since it's an enum that cannot possibly include all organisms the user might come up with.

I can see two ways forward:
- add this as training for the model: it won't capture the species (not in the enum) but it might capture the intent. Then you'll have an intent without an entity and you'll be asked again what species you want.
- tell the user that the intent is not recognised in the first place, i.e. do nothing.

Neither is perfect, the limitation being in using enums to capture entities. I don't know how to make a better capture algorithm though, as the definition of a species is kind of blurry.

**Comment by YingX97** [comment]
I think the first option's is better. Even though we can't identify a species, knowing the intent, we can just say, "Sorry, the species you asked for is unavailable....etc". It's makes the error clearer than doing nothing, I guess?.

**Comment by iosonofabio** [comment]
no we cannot say that. What we can say is that "we think you want to explore a species, but you haven't told us what species you want", which is not that useful

**Comment by iosonofabio** [comment]
fixed in 0.2.4
