### ISSUE TITLE
space in cell type and gene list

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#3]
The nlp failed to recognise the cell type when there a ‘ space’ between the name

- where are pericyte detected in human? ✅
- where are smooth muscle detected in human? ❎

**Comment by iosonofabio** [comment]
I tried to play with the capture regex for a while. It's quite tricky to get right I have to say.

I'm tempted to hack this for the time being using post-processing and come back to it if needed.

**Comment by iosonofabio** [comment]
This is now fixed in a suboptimal way using pre- and post-processing functions within the NLP `ask` function. Not ideal because it relies on a bunch of moving parts: regex capture of the mutli-word entity, cleanup of orphan entities after the NLP request, and autocorrection within the API backend.

Nonetheless, it's not too dirty and it worksin 0.1.14. Closing.
